### PR TITLE
[REG-1635] Add SDK link to homepage

### PR DESCRIPTION
**Pull request by vontell**
Adds the SDK url to the homepage for power users who want to jump right in. Assumes they know how to add git packages to Unity through the package manager. 

Screenshot 2024-03-12 at 12 35 25 PM

---

Find the pull request instructions [here](https://www.notion.so/regressiongg/Pull-Request-Process-0d57a7eb582a446983edfacafa406f1e?pvs=4)

Every reviewer and the owner of the PR should consider these points in their request (feel free to copy this checklist so you can fill it out yourself in the overall PR comment)

- [ ] The code is extensible and backward compatible
- [ ] New public interfaces are extensible and open to backward compatibility in the future
- [ ] If preparing to remove a field in the future (i.e. this PR removes an argument), the argument stays but is no longer functional, and attaches a deprecation warning. A linear task is also created to track this deletion task.
- [ ] Non-critical or potentially modifiable arguments are optional
- [ ] Breaking changes and the approach to handling them have been verified with the team (in the Linear task, design doc, or PR itself)
- [ ] The code is easy to read
- [ ] Unit tests are added for expected and edge cases
- [ ] Integration tests are added for expected and edge cases
- [ ] Functions and classes are documented
- [ ] Migrations for both up and down operations are completed
- [ ] A documentation PR is created and being reviewed for anything in this PR that requires knowledge to use
- [ ] Implications on other dependent code (i.e. sample games and sample bots) is considered, mentioned, and properly handled
- [ ] Style changes and other non-blocking changes are marked as non-blocking from reviewers

### CODE REVIEW

**Review by rcornwall-reg — APPROVED** [review]
[Non Blocking]
Linking directly to the package instead of the root project is a good idea, but I feel like we should have another README inside the package folder as well. It's always a bit jarring to me when I hit a repo and there's no README

**Review by RG-nAmKcAz — APPROVED** [review]
Approving, but the number of users that would do this without first reading what the package does seems like it would be small or near zero.

**Comment by vontell** [comment]
For reviewers: @rcornwall-reg the repo does have a readme, although it's in the root folder, not in the package subfolder. 

@RG-nAmKcAz definitely see what you are saying - I have found that I do use this option in other packages though when I've used them before - when I know what I want, I've used it before, and I don't want to dig through the docs for the package link.

**Comment by rcornwall-reg** [comment]
@vontell I know there's the root README. I was specifically talking about adding a second README to the subfolder you're directly linking to

**Pull request merged**
