### PR TITLE
[REG-1310] Add proper version to docs

### PR DESCRIPTION
**Pull request by vontell**
Finally adds a proper version to our download instructions so that users don't get stuck with rapidly-changing main.

A PR has also been opened for the SDK README.

### CODE REVIEW

**Review by RG-nAmKcAz — APPROVED** [review]
Approved, how are we planning to manage versioning/releases here?

I assume new release per cycle similar/same as the backend/ui ?

Are we going to align the version numbers or manage them separately ?

**Comment by RG-nAmKcAz** [comment]
@vontell You may want to update the tag to include the PR abby merged just now supporting nullable types in the SDK

**Review by abeizer — APPROVED** [review]

**Comment by vontell** [comment]
@RG-nAmKcAz yeah same process as we follow for the services. Good question on whether we should align them with the platform version... I think we should once we do a new release, makes the most sense to me for determining which SDK works with which release.

**Comment by vontell** [comment]
And yes will update that version!

**Pull request merged**
